using System.Diagnostics;

namespace FiresWinForms
{
    public static class RunCmd
    {
        public static string Run(string cmd, string path, int num, string serializedVals = "", bool save = false)
        {
            ProcessStartInfo start = new ProcessStartInfo
            {
                FileName = cmd,
                Arguments = string.Format("\"{0}\" {1} {2} {3}", path, num, ((save) ? "save" : "show"), serializedVals),
                UseShellExecute = false,// Do not use OS shell
                CreateNoWindow = true, // We don't need new window
                RedirectStandardOutput = true,// Any output, generated by application will be redirected back
                RedirectStandardError = true // Any error in standard output will be redirected back (for example exceptions)
            };
            using Process process = Process.Start(start);
            using StreamReader reader = process.StandardOutput;
            string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
            string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
            return result;
        }
    }
}
